### ISSUE TITLE
Deleting accounts breaks things

### ISSUE THREAD

**Issue by ghost** [isaacjwilliams/antisocial#5]
You get a 500 error if you delete accounts.

Also, profile pages don't work when the username has a space in ;)

**Comment by isaacjwilliams** [comment]
I know about the profile page business: but a 500 error on account deletion? Strange. That doesn't happen on localhost. I'll look into it, thanks.

**Comment by isaacjwilliams** [comment]
All right, that's all cleaned up. Thanks @charlw for the alert. :)
